[build]
    command = "npm install && npm run build"
  publish = "dist"
  base = "/"
  ignore = "false"  # Never skip build
  force = "true"    # Force build even if no changes detected

[build.environment]
  NODE_VERSION = "18"
  CI = "true"       # Ensure we're in CI mode
  NETLIFY_BUILD_SKIP = "false"  # Never skip build
  VITE_SUPABASE_URL = "https://wgzyssujuylspzruezlq.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indnenlzc3VqdXlsc3B6cnVlemxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNzI1OTYsImV4cCI6MjA3NjY0ODU5Nn0.6unQvAfZiI3o5HpQa3H5pOGoZD9WLZn5m9a-fw55WCI"

[build.processing]
  skip_processing = false  # Ensure processing is not skipped

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "vite"
  port = 3000
  publish = "dist"