// This file can be auto-generated by Supabase CLI in a real project
// For now, we define the types manually based on our schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      categories: {
        Row: {
          id: string
          name: string
          type: "income" | "expense"
          user_id: string
          icon: string | null
          color: string | null
          created_at: string
        }
        Insert: {
          name: string
          type: "income" | "expense"
          user_id: string
          icon?: string | null
          color?: string | null
        }
        Update: {
          name?: string
          type?: "income" | "expense"
          icon?: string | null
          color?: string | null
        }
      }
      transactions: {
        Row: {
          id: string
          amount: number
          description: string
          category_id: string
          user_id: string
          transaction_date: string
          type: "income" | "expense"
          created_at: string
          notes?: string
          attachment_url?: string
          updated_at?: string
        }
        Insert: {
          amount: number
          description: string
          category_id: string
          user_id: string
          transaction_date: string
          type: "income" | "expense"
          notes?: string
        }
        Update: {
          amount?: number
          description?: string
          category_id?: string
          transaction_date?: string
          notes?: string
        }
      }
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
        }
        Update: {
          full_name?: string | null
          avatar_url?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      reset_user_data: {
        Args: {}
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export type Category = Database['public']['Tables']['categories']['Row'];
export type Transaction = Database['public']['Tables']['transactions']['Row'];
export type Profile = Database['public']['Tables']['profiles']['Row'];
