name: Test CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'full'
        type: choice
        options:
        - build-only
        - deploy-staging
        - full

jobs:
  test-build:
    runs-on: ubuntu-latest
    if: inputs.test_type == 'build-only' || inputs.test_type == 'full'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Build for production
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    - name: Verify build artifacts
      run: |
        ls -la dist/
        echo "Build successful - artifacts created"

  test-deploy-staging:
    runs-on: ubuntu-latest
    if: inputs.test_type == 'deploy-staging' || inputs.test_type == 'full'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for production
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    - name: Deploy to Netlify (Staging Test)
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=dist --prod=false --message="Test deployment from CI/CD pipeline"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGING }}

    - name: Output deployment URL
      run: echo "Staging deployment completed. Check the Netlify dashboard for the preview URL."